# Copyright 2026 Google LLC
# Image generation service using gemini-3.1-flash-lite-image in global region
# and Google Cloud Storage uploader.

import re
import uuid
from typing import Any, Dict, Optional, Tuple
from google import genai
from google.cloud import storage
from google.genai import types

PROJECT_ID = "qwiklabs-gcp-04-2d53b9c1010c"
BUCKET_NAME = "bwg3-qwiklabs-gcp-04-2d53b9c1010c"
IMAGE_MODEL = "gemini-3.1-flash-lite-image"
IMAGE_REGION = "global"

_genai_client: Optional[genai.Client] = None
_storage_client: Optional[storage.Client] = None


def _get_genai_client() -> genai.Client:
    global _genai_client
    if _genai_client is None:
        _genai_client = genai.Client(
            vertexai=True,
            project=PROJECT_ID,
            location=IMAGE_REGION,
        )
    return _genai_client


def _get_storage_client() -> storage.Client:
    global _storage_client
    if _storage_client is None:
        _storage_client = storage.Client(project=PROJECT_ID)
    return _storage_client


def generate_and_upload_image(
    prompt: str,
    filename_prefix: str = "fpl_image",
) -> Tuple[bytes, str, str, str]:
    """Generates an image via gemini-3.1-flash-lite-image and uploads to the public GCS bucket.

    Returns:
        Tuple of (image_bytes, mime_type, filename, public_url)
    """
    client = _get_genai_client()
    clean_prefix = re.sub(r"[^a-zA-Z0-9_]+", "_", filename_prefix.lower())
    unique_suffix = uuid.uuid4().hex[:8]

    # Call gemini-3.1-flash-lite-image
    response = client.models.generate_content(
        model=IMAGE_MODEL,
        contents=prompt,
    )

    image_bytes = None
    mime_type = "image/jpeg"

    if response.candidates:
        for part in response.candidates[0].content.parts:
            if part.inline_data and part.inline_data.data:
                image_bytes = part.inline_data.data
                mime_type = part.inline_data.mime_type or "image/jpeg"
                break

    if not image_bytes:
        raise RuntimeError("No image was generated by gemini-3.1-flash-lite-image.")

    ext = "png" if "png" in mime_type else "jpg"
    filename = f"{clean_prefix}_{unique_suffix}.{ext}"

    # Upload to Cloud Storage
    storage_client = _get_storage_client()
    bucket = storage_client.bucket(BUCKET_NAME)
    blob = bucket.blob(filename)
    blob.upload_from_string(image_bytes, content_type=mime_type)

    public_url = f"https://storage.googleapis.com/{BUCKET_NAME}/{filename}"
    return image_bytes, mime_type, filename, public_url
