# Copyright 2026 Google LLC
# Video generation service using gemini-omni-flash-preview via Interactions API
# in the global region and Google Cloud Storage uploader.

import base64
import re
import uuid
from typing import Optional, Tuple
from google import genai
from google.cloud import storage

PROJECT_ID = "qwiklabs-gcp-04-2d53b9c1010c"
BUCKET_NAME = "bwg3-qwiklabs-gcp-04-2d53b9c1010c"
OMNI_MODEL = "gemini-omni-flash-preview"
OMNI_REGION = "global"

_genai_client: Optional[genai.Client] = None
_storage_client: Optional[storage.Client] = None


def _get_genai_client() -> genai.Client:
    global _genai_client
    if _genai_client is None:
        _genai_client = genai.Client(
            vertexai=True,
            project=PROJECT_ID,
            location=OMNI_REGION,
        )
    return _genai_client


def _get_storage_client() -> storage.Client:
    global _storage_client
    if _storage_client is None:
        _storage_client = storage.Client(project=PROJECT_ID)
    return _storage_client


def generate_and_upload_video(
    prompt: str,
    filename_prefix: str = "fpl_highlight",
) -> Tuple[bytes, str, str, str]:
    """Generates a short video via gemini-omni-flash-preview and uploads to the public GCS bucket.

    Returns:
        Tuple of (video_bytes, mime_type, filename, public_url)
    """
    client = _get_genai_client()
    clean_prefix = re.sub(r"[^a-zA-Z0-9_]+", "_", filename_prefix.lower())
    unique_suffix = uuid.uuid4().hex[:8]

    # Call gemini-omni-flash-preview using the Interactions API
    interaction = client.interactions.create(
        model=OMNI_MODEL,
        input=prompt,
        response_format={"type": "video"},
    )

    if not interaction.output_video or not interaction.output_video.data:
        raise RuntimeError("No video was generated by gemini-omni-flash-preview.")

    raw_data = interaction.output_video.data
    if isinstance(raw_data, str):
        try:
            video_bytes = base64.b64decode(raw_data)
        except Exception:
            video_bytes = raw_data.encode("latin1")
    else:
        video_bytes = bytes(raw_data)

    mime_type = interaction.output_video.mime_type or "video/mp4"
    ext = "mp4" if "mp4" in mime_type else "webm"
    filename = f"{clean_prefix}_{unique_suffix}.{ext}"

    # Upload to Cloud Storage directly from memory
    storage_client = _get_storage_client()
    bucket = storage_client.bucket(BUCKET_NAME)
    blob = bucket.blob(filename)
    blob.upload_from_string(video_bytes, content_type=mime_type)

    public_url = f"https://storage.googleapis.com/{BUCKET_NAME}/{filename}"
    return video_bytes, mime_type, filename, public_url
